# Generated by Django 4.0.6 on 2023-01-12 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_service_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Mobileno', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('service_catg_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(null=True)),
                ('prise', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('service_by', models.CharField(max_length=40)),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('service_prise', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='store_app_service_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('slnoo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='store_invoice_data_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('slnoo', models.IntegerField(blank=True, null=True)),
                ('prise', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('slno', models.CharField(max_length=30)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('MobileNo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Password', models.CharField(max_length=1000)),
                ('invoice_number', models.IntegerField(default=0, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('vendor_id', models.CharField(max_length=6)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('dev_limit', models.IntegerField()),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_staff', models.IntegerField(default=0)),
                ('s_gst_percent', models.CharField(max_length=30)),
                ('c_gst_percent', models.CharField(max_length=30)),
                ('current_billslno', models.CharField(max_length=50)),
                ('appointment_no', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('client_service_data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swalook.client_service_data')),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Discont', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('slno', models.CharField(blank=True, max_length=50, null=True)),
                ('s_gst', models.BigIntegerField(blank=True, null=True)),
                ('c_gst', models.BigIntegerField(blank=True, null=True)),
                ('grand_total', models.BigIntegerField(blank=True, null=True)),
                ('s_gst_percent', models.CharField(max_length=30)),
                ('c_gst_percent', models.CharField(max_length=30)),
                ('vendorname', models.CharField(max_length=30)),
            ],
            bases=('swalook.client_service_data',),
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('MobileNo', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('aadhar_id', models.CharField(max_length=12)),
                ('aadhar_id_img', models.ImageField(upload_to='media/staff/aadhar')),
                ('pan_id', models.CharField(max_length=12)),
                ('pan_id_img', models.ImageField(upload_to='media/staff/pan')),
                ('date_of_joined', models.DateField(max_length=300)),
                ('days_of_attend', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('present_staff_attendence', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPointTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cashback_Points', models.IntegerField()),
                ('service_cost', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('booking_date', models.DateField(null=True)),
                ('booking_time', models.CharField(blank=True, max_length=100, null=True)),
                ('service_slno', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
