# Generated by Django 4.0.6 on 2023-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='check_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
