# Generated by Django 4.0.6 on 2023-02-26 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0003_alter_invoice_c_gst_alter_invoice_s_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
