# Generated by Django 4.0.6 on 2023-02-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0004_invoice_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='store_invoice_data_service',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
