# Generated by Django 4.0.6 on 2023-03-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0005_alter_invoice_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_prise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='store_invoice_data_service',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='store_invoice_data_service',
            name='dicount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='store_invoice_data_service',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='store_invoice_data_service',
            name='taxableamt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='store_invoice_data_service',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
