# Generated by Django 4.0.6 on 2023-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0006_invoice_total_cgst_invoice_total_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
