# Generated by Django 4.0.6 on 2023-03-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0008_vendor_inv_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor_inv_data',
        ),
    ]
