# Generated by Django 4.0.6 on 2023-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0010_sallonprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Mobileno', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('service_catg_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(null=True)),
                ('total_prise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('service_by', models.CharField(max_length=40)),
                ('slno', models.CharField(blank=True, max_length=50, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('s_gst_percent', models.CharField(max_length=30)),
                ('c_gst_percent', models.CharField(max_length=30)),
                ('vendorname', models.CharField(max_length=30)),
                ('check_value', models.CharField(blank=True, max_length=30, null=True)),
                ('date_field', models.DateField()),
            ],
        ),
    ]
