# Generated by Django 4.0.6 on 2023-03-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0011_invoice_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_data',
            name='date_time',
        ),
    ]
