# Generated by Django 4.0.6 on 2023-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0012_remove_invoice_data_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_data',
            name='service_duration',
            field=models.CharField(default=20, max_length=30),
            preserve_default=False,
        ),
    ]
