# Generated by Django 4.0.6 on 2023-03-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0013_service_data_service_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='MobileNo',
            new_name='mobileno',
        ),
        migrations.RenameField(
            model_name='staffdetails',
            old_name='Name',
            new_name='staffname',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='aadhar_id',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='aadhar_id_img',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='date_of_joined',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='days_of_attend',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='pan_id',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='pan_id_img',
        ),
    ]
