# Generated by Django 4.0.6 on 2023-03-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0014_rename_mobileno_staffdetails_mobileno_and_more'),
    ]

    operations = [
    ]
