# Generated by Django 4.0.6 on 2023-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0018_alter_service_data_user_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_data',
            name='month',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoice_data',
            name='week',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
