# Generated by Django 4.0.6 on 2023-03-27 16:05

from django.db import migrations
from swalook.models import *

def migrate_to_product_model(apps, schema_editor):

     service = apps.get_model('swalook', 'invoice_data')
     for service in service.objects.all():
        date = str(service.date_field)

        service.week = date[8:10]
        service.month =  date[5:7]
        service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0019_invoice_data_month_invoice_data_week'),
    ]

    operations = [
         migrations.RunPython(migrate_to_product_model)
    ]
