# Generated by Django 4.0.6 on 2023-05-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swalook', '0021_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_account_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('billing_permission', models.BooleanField()),
                ('appointment_permission', models.BooleanField()),
                ('inventory_permission', models.BooleanField()),
                ('business_permission', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
