# Generated by Django 4.0.6 on 2023-05-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swalook', '0023_staff_account_details_staffname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_account_details',
            name='appointment_permission',
        ),
        migrations.RemoveField(
            model_name='staff_account_details',
            name='billing_permission',
        ),
        migrations.RemoveField(
            model_name='staff_account_details',
            name='business_permission',
        ),
        migrations.RemoveField(
            model_name='staff_account_details',
            name='inventory_permission',
        ),
    ]
