# Generated by Django 4.0.6 on 2023-08-15 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swalook', '0024_remove_staff_account_details_appointment_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_analysis', models.ImageField(null=True, upload_to='analysis')),
                ('month', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
